import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-renewable-ppa-settlement-curtailment-recovery",
  "engine": "recovery",
  "title": "Renewable PPA Settlement & Curtailment Recovery",
  "shortTitle": "PPA Settlement Recovery",
  "tagline": "Reconstruct settlements, value curtailment, and collect contractually owed energy revenue",
  "industry": "Renewable Energy Commercial Operations",
  "uiPort": 4556,
  "apiPort": 5556,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "PPA and market settlement leakage converted into recovered generation revenue",
  "valueNarrative": "Unify PPA terms, meter data, ISO settlements, nodal prices, curtailment instructions, RECs, and invoices.",
  "calculation": {
    "actualKey": "receivedSettlement",
    "expectedKey": "expectedSettlement",
    "actualLabel": "Received settlement",
    "expectedLabel": "Expected contract settlement",
    "varianceLabel": "Potential revenue recovery",
    "direction": "expected-minus-actual",
    "finding": "Generation, pricing, contract, and curtailment evidence indicate settlement revenue at risk.",
    "actions": [
      "Reconstruct interval generation and market settlement",
      "Apply PPA price, basis, loss, and escalation terms",
      "Validate curtailment eligibility and damages",
      "Invoice, dispute, and reconcile recovered revenue"
    ]
  }
},[
feature("ppa-and-amendment-library","PSR01","PPA and amendment library","Reconcile ppa and amendment library using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed ppa and amendment library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("asset-and-meter-registry","PSR02","Asset and meter registry","Reconcile asset and meter registry using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed asset and meter registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("interval-generation-ingestion","PSR03","Interval generation ingestion","Reconcile interval generation ingestion using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed interval generation ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("iso-settlement-ingestion","PSR04","ISO settlement ingestion","Reconcile iso settlement ingestion using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed iso settlement ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("contract-price-recalculation","PSR05","Contract price recalculation","Reconcile contract price recalculation using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed contract price recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("basis-and-loss-factor-validation","PSR06","Basis and loss-factor validation","Reconcile basis and loss-factor validation using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed basis and loss-factor validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("curtailment-event-reconstruction","PSR07","Curtailment event reconstruction","Reconcile curtailment event reconstruction using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed curtailment event reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("deemed-generation-calculation","PSR08","Deemed-generation calculation","Reconcile deemed-generation calculation using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed deemed-generation calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("liquidated-damages-recovery","PSR09","Liquidated-damages recovery","Reconcile liquidated-damages recovery using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed liquidated-damages recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("rec-delivery-reconciliation","PSR10","REC delivery reconciliation","Reconcile rec delivery reconciliation using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed rec delivery reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("availability-guarantee-tracking","PSR11","Availability guarantee tracking","Reconcile availability guarantee tracking using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed availability guarantee tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("invoice-and-settlement-matching","PSR12","Invoice and settlement matching","Reconcile invoice and settlement matching using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed invoice and settlement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("offtaker-dispute-package","PSR13","Offtaker dispute package","Reconcile offtaker dispute package using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed offtaker dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("receivable-and-credit-tracking","PSR14","Receivable and credit tracking","Reconcile receivable and credit tracking using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed receivable and credit tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]}),
feature("revenue-and-curtailment-analytics","PSR15","Revenue and curtailment analytics","Reconcile revenue and curtailment analytics using PPAs, meter intervals, ISO statements, nodal prices, basis adjustments, curtailment instructions, outage logs, and REC records.","Produce a governed revenue and curtailment analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["offtaker","Offtaker / ISO","text","Western Grid Market"],["facility","Generating Facility","text","Mesa Solar 250MW"],["receivedSettlement","Received Settlement","currency",2175000],["expectedSettlement","Expected Settlement","currency",2460000]],{amountField:"receivedSettlement",subjects:["Utility-scale solar PPA","Onshore wind PPA","Battery tolling agreement","Corporate virtual PPA","Community solar portfolio"]})
]);
